name: Build and Test Cache Module

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'cache/**'
  push:
    branches: [dev, main]
    paths:
      - 'cache/**'

jobs:
  build_test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "./cache/go.mod"

      - name: Build
        working-directory: ./cache
        run: go build -x

      - name: Test
        working-directory: ./cache
        run: go test -race -v ./...

      - name: Lint
        # lint even when a previous step failed
        if: ${{!cancelled()}}
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          working-directory: ./cache
          version: v1.52
          args: -v
