name: Build and Test Cache Module

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'cache/**'
  push:
    branches: [dev, main]
    paths:
      - 'cache/**'

jobs:
  build_test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

      - uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
        with:
          go-version-file: "./cache/go.mod"

      - name: Build
        working-directory: ./cache
        run: go build -x

      - name: Test
        working-directory: ./cache
        run: go test -race -v ./...

      - name: Lint
        # lint even when a previous step failed
        if: ${{!cancelled()}}
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
        with:
          working-directory: ./cache
          version: v1.52
          args: -v
